import '../entities/work_task.dart';

abstract final class WorkTaskCatalog {
  static const tasks = <WorkTask>[
    WorkTask(
      id: 1,
      jobId: 1,
      title: 'Müşteri desteği',
      description: 'Müşterilere yardımcı ol ve iletişim becerini geliştir.',
      energyCost: 20,
      durationHours: 8,
      salaryMultiplier: 1,
      performanceGain: 5,
      experienceGain: 4,
    ),
    WorkTask(
      id: 2,
      jobId: 1,
      title: 'Satış hedefi',
      description: 'Günün satış hedefini tamamla ve daha yüksek gelir kazan.',
      energyCost: 25,
      durationHours: 6,
      salaryMultiplier: 1.2,
      performanceGain: 7,
      experienceGain: 5,
    ),
    WorkTask(
      id: 3,
      jobId: 2,
      title: 'Vardiya planı',
      description: 'Ekibin vardiya planını hazırla ve operasyonu düzenle.',
      energyCost: 24,
      durationHours: 8,
      salaryMultiplier: 1,
      performanceGain: 5,
      experienceGain: 7,
    ),
    WorkTask(
      id: 4,
      jobId: 3,
      title: 'Bölge raporu',
      description: 'Mağaza sonuçlarını analiz et ve büyüme önerisi hazırla.',
      energyCost: 28,
      durationHours: 8,
      salaryMultiplier: 1,
      performanceGain: 4,
      experienceGain: 9,
    ),
    WorkTask(
      id: 5,
      jobId: 4,
      title: 'Finans kaydı',
      description: 'Günlük finans hareketlerini kaydet ve raporlamaya hazırla.',
      energyCost: 18,
      durationHours: 6,
      salaryMultiplier: 1,
      performanceGain: 6,
      experienceGain: 5,
    ),
    WorkTask(
      id: 6,
      jobId: 5,
      title: 'Bütçe analizi',
      description: 'Bütçe sapmalarını incele ve iyileştirme önerisi geliştir.',
      energyCost: 25,
      durationHours: 8,
      salaryMultiplier: 1,
      performanceGain: 5,
      experienceGain: 8,
    ),
    WorkTask(
      id: 7,
      jobId: 6,
      title: 'Rota planı',
      description: 'Sevkiyat rotalarını planla ve teslimat verimliliğini artır.',
      energyCost: 24,
      durationHours: 8,
      salaryMultiplier: 1.1,
      performanceGain: 5,
      experienceGain: 7,
    ),
  ];

  static List<WorkTask> forJob(int jobId) => tasks.where((task) => task.jobId == jobId).toList(growable: false);
}
