import '../entities/company_market_event.dart';
import '../entities/company_specialty.dart';

abstract final class CompanyMarketEventCatalog {
  static const events = <CompanyMarketEvent>[
    CompanyMarketEvent(
      id: 'demand_boom',
      title: 'Talep artışı',
      description: 'Müşteri talebi tüm şirket gelirlerini artırıyor.',
      category: CompanyMarketEventCategory.opportunity,
      specialty: CompanySpecialty.sales,
      revenuePercent: 15,
      payrollPercent: 0,
    ),
    CompanyMarketEvent(
      id: 'digital_transformation',
      title: 'Dijital dönüşüm dalgası',
      description: 'Yeni yatırımlar pazardaki harcamaları canlandırıyor.',
      category: CompanyMarketEventCategory.opportunity,
      specialty: CompanySpecialty.technology,
      revenuePercent: 8,
      payrollPercent: 3,
    ),
    CompanyMarketEvent(
      id: 'export_wave',
      title: 'İhracat siparişleri',
      description: 'Dış pazardan gelen siparişler lojistik gelirini büyütüyor.',
      category: CompanyMarketEventCategory.opportunity,
      specialty: CompanySpecialty.logistics,
      revenuePercent: 12,
      payrollPercent: 2,
    ),
    CompanyMarketEvent(
      id: 'public_investment',
      title: 'Yatırım teşvikleri',
      description: 'Yeni teşvikler finansmanı ve kurumsal talebi destekliyor.',
      category: CompanyMarketEventCategory.opportunity,
      specialty: CompanySpecialty.finance,
      revenuePercent: 10,
      payrollPercent: 1,
    ),
    CompanyMarketEvent(
      id: 'recession',
      title: 'Ekonomik durgunluk',
      description: 'Düşük talep günlük geliri baskılıyor.',
      category: CompanyMarketEventCategory.threat,
      specialty: CompanySpecialty.finance,
      revenuePercent: -12,
      payrollPercent: 0,
    ),
    CompanyMarketEvent(
      id: 'cost_pressure',
      title: 'Maliyet baskısı',
      description: 'İşletme maliyetleri yükselirken talep hafif daralıyor.',
      category: CompanyMarketEventCategory.threat,
      specialty: CompanySpecialty.logistics,
      revenuePercent: -5,
      payrollPercent: 8,
    ),
    CompanyMarketEvent(
      id: 'supply_disruption',
      title: 'Tedarik kesintisi',
      description:
          'Geciken teslimatlar geliri azaltıp operasyon yükünü artırıyor.',
      category: CompanyMarketEventCategory.threat,
      specialty: CompanySpecialty.operations,
      revenuePercent: -8,
      payrollPercent: 5,
    ),
    CompanyMarketEvent(
      id: 'price_war',
      title: 'Fiyat savaşı',
      description: 'Yoğun rekabet satış marjlarını geçici olarak düşürüyor.',
      category: CompanyMarketEventCategory.threat,
      specialty: CompanySpecialty.sales,
      revenuePercent: -10,
      payrollPercent: 2,
    ),
    CompanyMarketEvent(
      id: 'talent_shortage',
      title: 'Yetenek kıtlığı',
      description: 'Nitelikli çalışan maliyetleri geçici olarak yükseldi.',
      category: CompanyMarketEventCategory.workforce,
      specialty: CompanySpecialty.leadership,
      revenuePercent: 0,
      payrollPercent: 10,
    ),
    CompanyMarketEvent(
      id: 'wage_pressure',
      title: 'Ücret baskısı',
      description:
          'Çalışan beklentileri yükselirken güçlü ekipler üretimi koruyor.',
      category: CompanyMarketEventCategory.workforce,
      specialty: CompanySpecialty.leadership,
      revenuePercent: 3,
      payrollPercent: 8,
    ),
    CompanyMarketEvent(
      id: 'remote_efficiency',
      title: 'Uzaktan çalışma verimi',
      description:
          'Yeni çalışma düzeni verimi artırıp personel yükünü azaltıyor.',
      category: CompanyMarketEventCategory.workforce,
      specialty: CompanySpecialty.technology,
      revenuePercent: 5,
      payrollPercent: -4,
    ),
    CompanyMarketEvent(
      id: 'turnover_wave',
      title: 'İşten ayrılma dalgası',
      description: 'Ekip değişimleri teslimatları ve ücret bütçesini zorluyor.',
      category: CompanyMarketEventCategory.workforce,
      specialty: CompanySpecialty.operations,
      revenuePercent: -4,
      payrollPercent: 6,
    ),
    CompanyMarketEvent(
      id: 'balanced_market',
      title: 'Dengeli piyasa',
      description: 'Talep ve işletme maliyetleri normal seviyede.',
      category: CompanyMarketEventCategory.stable,
      specialty: CompanySpecialty.operations,
      revenuePercent: 0,
      payrollPercent: 0,
    ),
    CompanyMarketEvent(
      id: 'regional_fair',
      title: 'Bölgesel ticaret fuarı',
      description:
          'Yerel bağlantılar sınırlı fakat istikrarlı talep oluşturuyor.',
      category: CompanyMarketEventCategory.stable,
      specialty: CompanySpecialty.sales,
      revenuePercent: 4,
      payrollPercent: 1,
    ),
    CompanyMarketEvent(
      id: 'inventory_balance',
      title: 'Stok dengelenmesi',
      description: 'Tedarik planı gelir ve operasyon maliyetini iyileştiriyor.',
      category: CompanyMarketEventCategory.stable,
      specialty: CompanySpecialty.logistics,
      revenuePercent: 2,
      payrollPercent: -1,
    ),
    CompanyMarketEvent(
      id: 'process_standardization',
      title: 'Süreç standardizasyonu',
      description:
          'Düzenli iş akışı küçük fakat güvenli bir verim artışı sağlıyor.',
      category: CompanyMarketEventCategory.stable,
      specialty: CompanySpecialty.operations,
      revenuePercent: 3,
      payrollPercent: 0,
    ),
  ];
}
