import '../entities/company_competitor.dart';
import '../entities/company_specialty.dart';

abstract final class CompanyCompetitorCatalog {
  static const competitors = <CompanyCompetitor>[
    CompanyCompetitor(
      id: 'pusula',
      name: 'Pusula Girişim',
      leaderName: 'Ece Yalın',
      personality: 'Cesur, çevik ve yenilik odaklı',
      specialty: CompanySpecialty.technology,
      baseStrength: 28,
      growthFocus: 'Ar-Ge ve çevik ürün geliştirme',
      branchIntervalDays: 25,
      hiringIntervalDays: 7,
      dailyFinanceGrowth: 180,
      dailyProjectProgress: 6,
      strengthTitle: 'Hızlı yenilik',
      strengthDescription: 'Dijital dönüşümde rakip gücü +8.',
      strongEventId: 'digital_transformation',
      strongEventBonus: 8,
      weaknessTitle: 'Kırılgan maliyet yapısı',
      weaknessDescription: 'Maliyet baskısında rakip gücü -6.',
      weakEventId: 'cost_pressure',
      weakEventPenalty: 6,
    ),
    CompanyCompetitor(
      id: 'anadolu',
      name: 'Anadolu Ortaklık',
      leaderName: 'Mert Özkan',
      personality: 'Temkinli, dayanıklı ve ortaklıkçı',
      specialty: CompanySpecialty.operations,
      baseStrength: 38,
      growthFocus: 'Yerel ortaklık ve dengeli operasyon',
      branchIntervalDays: 18,
      hiringIntervalDays: 6,
      dailyFinanceGrowth: 230,
      dailyProjectProgress: 5,
      strengthTitle: 'Kriz dayanıklılığı',
      strengthDescription: 'Ekonomik durgunlukta rakip gücü +7.',
      strongEventId: 'recession',
      strongEventBonus: 7,
      weaknessTitle: 'Yavaş dönüşüm',
      weaknessDescription: 'Dijital dönüşümde rakip gücü -5.',
      weakEventId: 'digital_transformation',
      weakEventPenalty: 5,
    ),
    CompanyCompetitor(
      id: 'kuzey',
      name: 'Kuzey Holding',
      leaderName: 'Selin Karaca',
      personality: 'Disiplinli, verimli ve süreç odaklı',
      specialty: CompanySpecialty.logistics,
      baseStrength: 50,
      growthFocus: 'Lojistik ağ ve süreç verimliliği',
      branchIntervalDays: 14,
      hiringIntervalDays: 5,
      dailyFinanceGrowth: 300,
      dailyProjectProgress: 4,
      strengthTitle: 'Maliyet disiplini',
      strengthDescription: 'Maliyet baskısında rakip gücü +7.',
      strongEventId: 'cost_pressure',
      strongEventBonus: 7,
      weaknessTitle: 'Katı kurum kültürü',
      weaknessDescription: 'Yetenek kıtlığında rakip gücü -5.',
      weakEventId: 'talent_shortage',
      weakEventPenalty: 5,
    ),
    CompanyCompetitor(
      id: 'atlas',
      name: 'Atlas Global',
      leaderName: 'Arda Vural',
      personality: 'Agresif, iddialı ve satış odaklı',
      specialty: CompanySpecialty.sales,
      baseStrength: 64,
      growthFocus: 'Satış, sermaye ve hızlı ölçekleme',
      branchIntervalDays: 12,
      hiringIntervalDays: 4,
      dailyFinanceGrowth: 380,
      dailyProjectProgress: 5,
      strengthTitle: 'Küresel satış ağı',
      strengthDescription: 'Talep artışında rakip gücü +8.',
      strongEventId: 'demand_boom',
      strongEventBonus: 8,
      weaknessTitle: 'Yüksek sabit gider',
      weaknessDescription: 'Ekonomik durgunlukta rakip gücü -7.',
      weakEventId: 'recession',
      weakEventPenalty: 7,
    ),
  ];
}
