import '../../../skills/domain/entities/skill_id.dart';
import '../entities/job.dart';

abstract final class JobCatalog {
  static const version = 3;
  static const jobs = _jobs;

  static Job? findById(int? id) {
    for (final job in jobs) {
      if (job.id == id) {
        return job;
      }
    }
    return null;
  }

  static List<Job> careerPathFor(Job job) => List.unmodifiable(
    jobs.where((candidate) => candidate.careerTrack == job.careerTrack).toList()
      ..sort((left, right) => left.level.compareTo(right.level)),
  );
}

const _jobs = <Job>[
  Job(
    id: 1,
    title: 'Mağaza asistanı',
    company: 'Bereket Market',
    description: 'Müşteri ve satış süreçlerine destek ol.',
    salary: 120,
    minimumKnowledge: 0,
    minimumExperience: 0,
    careerTrack: 'satış ve perakende',
    level: 1,
    nextJobId: 2,
    skillRequirements: {SkillId.communication: 0, SkillId.sales: 0},
  ),
  Job(
    id: 2,
    title: 'Mağaza sorumlusu',
    company: 'Bereket Market',
    description: 'Mağaza operasyonunu ve ekibi yönet.',
    salary: 220,
    minimumKnowledge: 12,
    minimumExperience: 10,
    careerTrack: 'satış ve perakende',
    level: 2,
    nextJobId: 3,
    skillRequirements: {SkillId.sales: 20, SkillId.leadership: 12},
  ),
  Job(
    id: 3,
    title: 'Bölge yöneticisi',
    company: 'Bereket Market',
    description: 'Bölgesel satış ve büyüme planlarını yönet.',
    salary: 350,
    minimumKnowledge: 20,
    minimumExperience: 25,
    careerTrack: 'satış ve perakende',
    level: 3,
    nextJobId: 7,
    managementRole: true,
    skillRequirements: {
      SkillId.sales: 30,
      SkillId.leadership: 25,
      SkillId.analysis: 15,
    },
  ),
  Job(
    id: 7,
    title: 'Satış müdürü',
    company: 'Bereket Market',
    description: 'Satış stratejisini ve ticari hedefleri yönet.',
    salary: 520,
    minimumKnowledge: 32,
    minimumExperience: 45,
    careerTrack: 'satış ve perakende',
    level: 4,
    nextJobId: 8,
    skillRequirements: {
      SkillId.sales: 42,
      SkillId.leadership: 35,
      SkillId.negotiation: 25,
    },
  ),
  Job(
    id: 8,
    title: 'Ticari direktör',
    company: 'Bereket Market',
    description: 'Şirketin ticari büyüme hattına liderlik et.',
    salary: 760,
    minimumKnowledge: 48,
    minimumExperience: 70,
    careerTrack: 'satış ve perakende',
    level: 5,
    skillRequirements: {
      SkillId.sales: 55,
      SkillId.leadership: 50,
      SkillId.negotiation: 40,
    },
  ),
  Job(
    id: 4,
    title: 'Muhasebe asistanı',
    company: 'Köprü Finans',
    description: 'Finans kayıtlarını düzenle ve nakit akışını takip et.',
    salary: 180,
    minimumKnowledge: 8,
    minimumExperience: 5,
    careerTrack: 'finans',
    level: 1,
    nextJobId: 5,
    skillRequirements: {SkillId.accounting: 12, SkillId.analysis: 8},
  ),
  Job(
    id: 5,
    title: 'Finans uzmanı',
    company: 'Köprü Finans',
    description: 'Bütçe analizleri hazırla ve finans kararlarına katkı sağla.',
    salary: 320,
    minimumKnowledge: 20,
    minimumExperience: 20,
    careerTrack: 'finans',
    level: 2,
    nextJobId: 9,
    skillRequirements: {SkillId.accounting: 25, SkillId.analysis: 20},
  ),
  Job(
    id: 9,
    title: 'Finans yöneticisi',
    company: 'Köprü Finans',
    description: 'Finans planlamasını ve risk yönetimini yürüt.',
    salary: 470,
    minimumKnowledge: 32,
    minimumExperience: 40,
    careerTrack: 'finans',
    level: 3,
    nextJobId: 10,
    managementRole: true,
    skillRequirements: {
      SkillId.accounting: 38,
      SkillId.analysis: 32,
      SkillId.leadership: 15,
    },
  ),
  Job(
    id: 10,
    title: 'Mali işler müdürü',
    company: 'Köprü Finans',
    description: 'Mali işler ekibine ve şirket bütçesine liderlik et.',
    salary: 650,
    minimumKnowledge: 45,
    minimumExperience: 62,
    careerTrack: 'finans',
    level: 4,
    nextJobId: 11,
    skillRequirements: {
      SkillId.accounting: 50,
      SkillId.analysis: 45,
      SkillId.leadership: 30,
    },
  ),
  Job(
    id: 11,
    title: 'Finans direktörü',
    company: 'Köprü Finans',
    description: 'Şirketin finansal stratejisini belirle.',
    salary: 900,
    minimumKnowledge: 60,
    minimumExperience: 90,
    careerTrack: 'finans',
    level: 5,
    skillRequirements: {
      SkillId.accounting: 65,
      SkillId.analysis: 60,
      SkillId.leadership: 45,
    },
  ),
  Job(
    id: 6,
    title: 'Lojistik koordinatörü',
    company: 'Ufuk Lojistik',
    description: 'Tedarik akışını ve operasyonların zamanlamasını planla.',
    salary: 280,
    minimumKnowledge: 15,
    minimumExperience: 15,
    careerTrack: 'lojistik',
    level: 1,
    nextJobId: 12,
    skillRequirements: {SkillId.logistics: 15, SkillId.operations: 10},
  ),
  Job(
    id: 12,
    title: 'Tedarik planlama uzmanı',
    company: 'Ufuk Lojistik',
    description: 'Tedarik ve stok planını optimize et.',
    salary: 390,
    minimumKnowledge: 25,
    minimumExperience: 30,
    careerTrack: 'lojistik',
    level: 2,
    nextJobId: 13,
    skillRequirements: {SkillId.logistics: 28, SkillId.analysis: 15},
  ),
  Job(
    id: 13,
    title: 'Operasyon yöneticisi',
    company: 'Ufuk Lojistik',
    description: 'Saha operasyonlarını ve süreç performansını yönet.',
    salary: 540,
    minimumKnowledge: 38,
    minimumExperience: 48,
    careerTrack: 'lojistik',
    level: 3,
    nextJobId: 14,
    managementRole: true,
    skillRequirements: {
      SkillId.operations: 38,
      SkillId.logistics: 35,
      SkillId.leadership: 20,
    },
  ),
  Job(
    id: 14,
    title: 'Bölge lojistik müdürü',
    company: 'Ufuk Lojistik',
    description: 'Bölgesel dağıtım ağını ve ekipleri yönet.',
    salary: 720,
    minimumKnowledge: 50,
    minimumExperience: 70,
    careerTrack: 'lojistik',
    level: 4,
    nextJobId: 15,
    skillRequirements: {
      SkillId.logistics: 50,
      SkillId.operations: 48,
      SkillId.leadership: 35,
    },
  ),
  Job(
    id: 15,
    title: 'Tedarik zinciri direktörü',
    company: 'Ufuk Lojistik',
    description: 'Tedarik zinciri stratejisini ve büyümeyi yönet.',
    salary: 980,
    minimumKnowledge: 65,
    minimumExperience: 100,
    careerTrack: 'lojistik',
    level: 5,
    skillRequirements: {
      SkillId.logistics: 68,
      SkillId.operations: 65,
      SkillId.leadership: 50,
    },
  ),
  Job(
    id: 16,
    title: 'Dijital operasyon asistanı',
    company: 'Yeni Ufuk Teknoloji',
    description: 'Dijital süreçlere ve günlük operasyonlara destek ol.',
    salary: 240,
    minimumKnowledge: 10,
    minimumExperience: 8,
    careerTrack: 'dijital ve operasyon',
    level: 1,
    nextJobId: 17,
    skillRequirements: {SkillId.digital: 12, SkillId.operations: 10},
  ),
  Job(
    id: 17,
    title: 'Dijital ürün uzmanı',
    company: 'Yeni Ufuk Teknoloji',
    description: 'Dijital ürün akışını ve kullanıcı verisini incele.',
    salary: 410,
    minimumKnowledge: 24,
    minimumExperience: 25,
    careerTrack: 'dijital ve operasyon',
    level: 2,
    nextJobId: 18,
    skillRequirements: {SkillId.digital: 30, SkillId.analysis: 18},
  ),
  Job(
    id: 18,
    title: 'İş analisti',
    company: 'Yeni Ufuk Teknoloji',
    description: 'Veriden içgörü çıkar ve süreç geliştirme önerileri üret.',
    salary: 570,
    minimumKnowledge: 38,
    minimumExperience: 45,
    careerTrack: 'dijital ve operasyon',
    level: 3,
    nextJobId: 19,
    skillRequirements: {
      SkillId.analysis: 42,
      SkillId.digital: 35,
      SkillId.creativity: 20,
    },
  ),
  Job(
    id: 19,
    title: 'Operasyon ürün müdürü',
    company: 'Yeni Ufuk Teknoloji',
    description: 'Ürün ve operasyon ekiplerini ortak hedefte buluştur.',
    salary: 760,
    minimumKnowledge: 52,
    minimumExperience: 68,
    careerTrack: 'dijital ve operasyon',
    level: 4,
    nextJobId: 20,
    skillRequirements: {
      SkillId.operations: 52,
      SkillId.leadership: 40,
      SkillId.digital: 45,
    },
  ),
  Job(
    id: 20,
    title: 'Dijital dönüşüm direktörü',
    company: 'Yeni Ufuk Teknoloji',
    description: 'Şirketin dijital dönüşüm stratejisini yönet.',
    salary: 1050,
    minimumKnowledge: 68,
    minimumExperience: 100,
    careerTrack: 'dijital ve operasyon',
    level: 5,
    skillRequirements: {
      SkillId.digital: 70,
      SkillId.leadership: 60,
      SkillId.creativity: 45,
    },
  ),
];
